name: Deploy LAMP App (Single Server)

on:
  push:
    branches:
      - master
      - beta

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_KEY }}" > key.pem
        chmod 600 key.pem

    - name: Debug key file (TEMP)
      run: |
        file key.pem
        head -n 5 key.pem

    - name: Determine target directory
      id: target
      run: |
        if [[ "${GITHUB_REF##*/}" == "master" ]]; then
          echo "dir=/var/www/html" >> $GITHUB_OUTPUT
        elif [[ "${GITHUB_REF##*/}" == "beta" ]]; then
          echo "dir=/var/www/beta" >> $GITHUB_OUTPUT
        else
          echo "Unsupported branch"
          exit 1
        fi

    - name: Rsync to server
      run: |
        rsync -avz -e "ssh -i key.pem -o StrictHostKeyChecking=no" ./public_html/ deploy@cop4331project.online:${{ steps.target.outputs.dir }}/

    - name: Clean up
      run: rm -f key.pem
